/**
 * C-PROP-004: generation determinism — double generation is
 * byte-identical, and any single mutation of output fails the compare.
 * C-ADV-003: drift against the committed corpus — the committed schemas
 * equal regenerated bytes file by file, and a hand-edited file is named.
 */
import { describe, expect, it } from 'vitest'
import { generateArtifacts } from '../schema/generation.js'
import { committedSchemas, digest } from './helpers.js'

describe('generation determinism (C-PROP-004)', () => {
  it('double generation is byte-identical', async () => {
    const first = await generateArtifacts()
    const second = await generateArtifacts()
    expect([...first.keys()]).toEqual([...second.keys()])
    for (const [relPath, content] of first) {
      expect(second.get(relPath)).toBe(content)
    }
  })

  it('any single mutation of output fails the comparison', async () => {
    const generated = await generateArtifacts()
    for (const [relPath, content] of generated) {
      const tampered = content.replace('"type": "object"', '"type": "object" ')
      expect(tampered).not.toBe(content)
      expect(digest(tampered)).not.toBe(digest(content))
      void relPath
    }
  })
})

describe('drift against committed output (C-ADV-003)', () => {
  it('committed schemas equal regenerated bytes, file by file', async () => {
    const generated = await generateArtifacts()
    const committed = committedSchemas()
    for (const [relPath, content] of generated) {
      expect(committed.get(relPath), `schemas/${relPath} missing or drifted`).toBe(content)
    }
  })

  it('a hand-edited file is named by the comparison', async () => {
    const generated = await generateArtifacts()
    const committed = new Map(committedSchemas())
    const [firstPath] = [...generated.keys()]
    expect(firstPath).toBeDefined()
    committed.set(firstPath ?? '', `${committed.get(firstPath ?? '') ?? ''} `)
    const divergent = [...generated].filter(
      ([relPath, content]) => committed.get(relPath) !== content,
    )
    expect(divergent.map(([relPath]) => relPath)).toEqual([firstPath])
  })
})
