/**
 * Events-side drift and determinism (C-PROP-004, C-ADV-003): this
 * package's generated artifacts equal the committed `schemas/` bytes. The
 * corpus-wide scans (neutrality, slots, ledger, inertness) run in
 * `@secure-home/contracts`' conformance suite over the whole committed
 * tree, this package's output included.
 */
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { generateArtifacts } from './generation.js'

const here = dirname(fileURLToPath(import.meta.url))
const schemasRoot = resolve(here, '../../..', 'schemas')

describe('events generation drift (C-ADV-003, C-PROP-004)', () => {
  it('double generation is byte-identical', async () => {
    const first = await generateArtifacts()
    const second = await generateArtifacts()
    for (const [relPath, content] of first) {
      expect(second.get(relPath)).toBe(content)
    }
  })

  it('committed schemas equal regenerated bytes, file by file', async () => {
    for (const [relPath, content] of await generateArtifacts()) {
      const committed = readFileSync(join(schemasRoot, relPath), 'utf8')
      expect(committed, `schemas/${relPath} drifted from authored source`).toBe(content)
    }
  })
})
