/**
 * FROZEN — evidence-bundle contract version 1.0.0, superseded by 2.0.0
 * (runner-contract-corrections D3: published versions are retained and
 * still generated; the identity ledger strictly appends). This module
 * exists only so `schemas/evidence-bundle/1.0.0.json` regenerates
 * byte-identically; it is not exported from the package index and no
 * consumer may import it. Do not edit: its generated bytes are anchored
 * by the ledger row `evidence-bundle@1.0.0`. Unchanged sub-shapes are
 * the same instances the v2 bundle uses.
 */
import { z } from 'zod'
import {
  AdapterId,
  CapabilityGrant,
  Digest,
  GateResults,
  ProfileIdentity,
  SemVer,
} from '@secure-home/contracts'
import {
  ArtifactEntry,
  ChangeSets,
  EVIDENCE_BUNDLE_ID,
  EvidenceOperation,
  EvidenceTiming,
  Principal,
} from './evidence.js'
import { RunId, RunOutcome } from './run-record.js'

export const EVIDENCE_BUNDLE_V1_VERSION = '1.0.0' as const

const EvidenceIdentitiesV1 = z.strictObject({
  run_id: RunId,
  profile: ProfileIdentity,
  image_digest: Digest,
  argv_digest: Digest,
  /** Opaque data — never a schema branch. */
  runtime: z.string().min(1),
  provider: z.string().min(1),
  adapter: AdapterId,
})

export const EvidenceBundleV1 = z.strictObject({
  contract_id: z.literal(EVIDENCE_BUNDLE_ID),
  contract_version: z.literal(EVIDENCE_BUNDLE_V1_VERSION),
  identities: EvidenceIdentitiesV1,
  principal: Principal,
  granted_capabilities: CapabilityGrant,
  operations: z.strictObject({
    attempted: z.array(EvidenceOperation),
    permitted: z.array(EvidenceOperation),
    denied: z.array(EvidenceOperation),
  }),
  gate_results: GateResults,
  artifacts: z.array(ArtifactEntry),
  change_sets: ChangeSets,
  outcome: RunOutcome,
  timing: EvidenceTiming,
})

SemVer.parse(EVIDENCE_BUNDLE_V1_VERSION)
