/**
 * FROZEN — path-policy contract version 1.0.0, superseded by 2.0.0
 * (runner-contract-corrections D3: published versions are retained and
 * still generated; the identity ledger strictly appends). This module
 * exists only so `schemas/path-policy/1.0.0.json` regenerates
 * byte-identically; it is not exported from the package index and no
 * consumer may import it. Do not edit: its generated bytes are anchored
 * by the ledger row `path-policy@1.0.0`.
 */
import { z } from 'zod'
import { SemVer } from '../primitives/index.js'
import { PATH_POLICY_ID } from './path-policy.js'

export const PATH_POLICY_V1_VERSION = '1.0.0' as const

export const PathPolicyV1 = z.strictObject({
  contract_id: z.literal(PATH_POLICY_ID),
  contract_version: z.literal(PATH_POLICY_V1_VERSION),
  allowed_write_roots: z.array(z.string().min(1)),
  prohibited_rules: z.array(z.string().min(1)),
  max_files: z.int().positive(),
  max_total_bytes: z.int().positive(),
  max_file_bytes: z.int().positive(),
})

SemVer.parse(PATH_POLICY_V1_VERSION)
